<html dir='ltr'>
<head>
<meta http-equiv='pics-label' content='(pics-1.1 'http://www.icra.org/ratingsv02.html' comment 'Single file v2.0' l gen true for 'http://windowsupdate.microsoft.com'  r (nz 1 vz 1 lz 1 oz 1 cz 1) 'http://www.rsac.org/ratingsv01.html' l gen true for 'http://windowsupdate.microsoft.com'  r (n 0 s 0 v 0 l 0))' />
<meta http-equiv='Content-Type' content='text/html;charset=windows-1252' />
<meta http-equiv='MSThemeCompatible' content='yes' />
<title>Microsoft Windows Update</title>
<meta name='MSSmartTagsPreventParsing' content='yes' />
<!--Copyright (c) Microsoft Corporation.  All rights reserved.-->
<script language='JScript' type='text/javascript' src='shared/js/tgar.js'></script>
<script language='JScript' type='text/javascript' src='shared/js/content.js'></script>
<link rel='stylesheet' type='text/css' href='shared/css/hcp.css' />
<link rel='stylesheet' type='text/css' href='shared/css/content.css' />

	<script language="javascript">
	var oWindow
		function fnOpenDriverInfo(){
			oWindow = window.open("driversquery.xml","DriverInfo","toolbar=0,menubar=0,scrollbars=1");
			oWindow.focus();
		}
	</script>
	</head>
	<body onload="fnInit(-1, -1);">
		<span class="sys-font-heading3 sys-rhp-color-title">Windows Update Privacy Statement</span><br />
		Last updated 1/8/2004<P>			
		Microsoft is committed to protecting your privacy.<P>
		<b>What data is collected – and why</b><br />
		Windows Update collects general system information from your computer with each visit, so that you receive the updates that work best with your computer. The information is also used to generate aggregate statistics about how the Windows Update website is used and which systems need support, so that we can improve our service. This information includes:<br /><br />
		<div style="margin-left:5px;">
		<UL>
			<li>Computer make and model</li>
			<li>Version information for the operating system, browser, and Microsoft software for which updates might be available</li>
			<li>Plug and Play ID numbers of hardware devices </li>
			<li>Region and Language setting </li>
			<li><span title="A large number generated by Windows that uniquely identifies a computer. The GUID does not contain any information that can be used to identify you.">Globally Unique Identifier (GUID)</span></li>
			<li>Product ID and Product Key </li>
			<li>BIOS name, revision number, and revision date </li>
		</UL><P></div>
		<span title="The set of technology standards and technical specifications that enable information to be routed from one network to another over the Internet. It is the way networks exchange data with each other.">Your Internet Protocol (IP) address is logged when you connect to the Windows Update site, but this address will only be used to generate aggregate statistics.</span><P>
		<b>How is this data used?</b><br />
		Windows Update collects the Product ID and Product Key to confirm that you are running a validly licensed copy of Windows. The Product ID and Product Key collected are not retained after you are finished using Windows Update, unless the Product ID is not valid.<p>To generate accurate statistics, Windows Update evaluates a Globally Unique Identifier (GUID) that is stored on your computer to uniquely identify it. The GUID does not contain any information that can be used to identify you. A GUID is assigned and tracked in the following cases:<P>
		<div style="margin-left:30px;">
		<ul>
			<li>To provide customers with the best possible service, Windows Update tracks and records the number of individual computers that visit the site and whether the download and installation of specific updates succeeded or failed. Windows Update records the GUID of the computer that attempted the download, the ID of the item that was requested, whether updates were required, and the configuration information listed above.<p></li>
			<li>Windows Update logs an additional GUID if you provide responses about whether help and troubleshooting articles were useful in resolving your problem. This allows Windows Update to provide you with increasingly helpful and relevant information.<p></li>
			<li>Microsoft collects information about the pages our customers visit within microsoft.com, including Windows Update. This information might include: your IP address, browser type, operating system, domain name, the time at which you accessed the site, and referring website addresses. This site visitation data is identified only by a unique ID number used solely for this purpose.<p></li>
		</ul>
		</div>
		<b>About surveys</b><br />
		Occasionally you might be invited to participate in a survey about the way you use the Windows Update website. Each survey includes a privacy statement that details the terms and use of any information submitted with that survey.<P>
		<b>View sample data</b><br />
		If you have additional questions about the computer information being evaluated by Windows Update, you can 
		<a href="javascript:fnOpenDriverInfo();"> view a sample of the information Microsoft will collect from your computer</a>
		. Note the data provided is sample data only—individual results may vary based on your specific computer configuration.<P>
		<iframe name='eReporting' src='blank.aspx' noresize='yes' height='0px' width='0px' style='display:none;' />
	</body>
</html>
