name: Download Windows Update V4 from Wayback Machine

on:
  workflow_dispatch:

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install wayback_machine_downloader
      run: gem install wayback_machine_downloader

    - name: Download archived website
      run: wayback_machine_downloader https://v4.windowsupdate.microsoft.com --directory windowsupdate_v4
      # Replace https://example.com with the website you want to download

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Download and update archived website" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/whistl353/archived-microsoft-resources.git
        git push

