name: Download Windows Update V3 from Wayback Machine

on:
  workflow_dispatch:

jobs:
  download_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Wayback Machine Downloader
        run: gem install wayback_machine_downloader
      - name: Download Site
        run: wayback_machine_downloader http://v4.windowsupdate.microsoft.com -d ./windowsupdate_v4
      - name: Commit and push changes
        run: |
          git config --local user.email "whistl353@github.com"
          git config --local user.name "whistl353"
          git add windowsupdate_v4
          git commit -m "Update website archive from Wayback Machine"
          git push
